### Matrices

In [1]:
import numpy as np

#### Squre Matrix

In [6]:
S = np.random.randn(3,3)

In [7]:
print(S)

[[ 0.78672266 -0.39946853 -0.24767322]
 [-0.63584958 -0.04194513 -0.36498977]
 [ 0.39643493  0.9605663   0.85094378]]


#### Rectangular Matrix

In [8]:
R = np.random.randn(3,2)

In [5]:
print(R)

[[-0.45308569 -2.14165469]
 [ 1.49405739  0.55322591]
 [-0.74577726 -0.06924237]
 [ 0.94447157 -2.04036923]
 [-2.24942672  1.67830297]]


##### Identity Matrix

In [9]:
I = np.eye(3)

In [10]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
